#FROM --platform=linux/amd64 cordmaur/geospatial_minimal
#FROM nvidia/cuda:11.0.3-base-ubuntu18.04
#FROM ghcr.io/osgeo/gdal:ubuntu-full-latest
#FROM ghcr.io/osgeo/gdal:ubuntu-small-latest
#FROM osgeo/gdal:ubuntu-small-3.6.3
FROM osgeo/gdal:ubuntu-small-3.1.2

# Set non-interactive environment variables
ENV DEBIAN_FRONTEND=noninteractive
ENV TZ=Etc/UTC

# Update and install necessary dependencies
RUN apt-get update && apt-get install -y --no-install-recommends wget gnupg2 software-properties-common build-essential curl && rm -rf /var/lib/apt/lists/*

# Add the NVIDIA package repository for CUDA 11.0
RUN wget https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2004/x86_64/cuda-keyring_1.0-1_all.deb && dpkg -i cuda-keyring_1.0-1_all.deb && rm -f cuda-keyring_1.0-1_all.deb && apt-get update

# Install CUDA 11.0 Toolkit
RUN apt-get install -y --no-install-recommends cuda-toolkit-11-1 && rm -rf /var/lib/apt/lists/*

RUN apt-get install -y lsb-release
RUN apt-get update && apt-get install -y fish
## Set environment variables for CUDA
ENV PATH=/usr/local/cuda/bin:$PATH
ENV LD_LIBRARY_PATH=/usr/local/cuda/lib64:$LD_LIBRARY_PATH

RUN apt-get update && apt-get install -y git cmake build-essential libboost-program-options-dev libboost-filesystem-dev libboost-graph-dev libboost-regex-dev libboost-system-dev libboost-test-dev libeigen3-dev libsuitesparse-dev libfreeimage-dev libgoogle-glog-dev libgflags-dev libglew-dev qtbase5-dev libqt5opengl5-dev libcgal-dev

RUN apt-get install libatlas-base-dev libsuitesparse-dev
RUN git clone https://ceres-solver.googlesource.com/ceres-solver && cd ceres-solver && git checkout facb199f3eda902360f9e1d5271372b7e54febe1 && mkdir build && cd build && cmake .. -DBUILD_TESTING=OFF -DBUILD_EXAMPLES=OFF && make -j8 && make install && cd ../../ && rm -rf ceres-solver

RUN apt-get install -y curl
RUN curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py && python3 get-pip.py
RUN pip install numpy
RUN pip install python-dateutil
RUN pip install imageio
RUN pip install utm
RUN pip install scipy
RUN pip install pyquaternion
RUN pip install pyproj
RUN pip install pymap3d
RUN pip install matplotlib
RUN apt-get install -y python3-dev
RUN pip install opencv-python --verbose
RUN pip install --upgrade numpy==1.23.4
RUN pip install numpy-groupies
RUN pip uninstall -y opencv-python
RUN pip install opencv-python-headless
RUN apt-get install libxcb-xinerama0
RUN apt-get install -y xvfb


CMD bash
